version: '3.3'

services:
  fastapi:
    build: .
    ports:
      - "4000:4000"
    environment:
      - KAFKA_BROKER=kafka1:9092
    volumes:
      - .:/app
    networks:
      tbnet:
        ipv4_address: 172.20.0.11

  topic-init:
    image: bitnami/kafka:3.5
    container_name: topic-init
    depends_on:
      - kafka1
    volumes:
      - ./create_topics.sh:/create_topics.sh
    entrypoint: ["bash", "-c", "sh create_topics.sh"]
    networks:
      tbnet:
        ipv4_address: 172.20.0.12

  jobmanager:
    image: flink:1.9.3
    container_name: jmanager
    command: jobmanager
    expose:
      - "6123"
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - JOB_MANAGER_REST_PORT=8081
    networks:
      tbnet:
        ipv4_address: 172.20.0.2

  taskmanager1:
    image: flink:1.9.3
    container_name: tmanager1
    command: taskmanager
    depends_on:
      - jobmanager
    links:
      - jobmanager
    expose:
      - "6121"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      tbnet:
        ipv4_address: 172.20.0.3

  taskmanager2:
    image: flink:1.9.3
    container_name: tmanager2
    command: taskmanager
    depends_on:
      - jobmanager
    links:
      - jobmanager
    expose:
      - "6122"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      tbnet:
        ipv4_address: 172.20.0.4

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      tbnet:
        ipv4_address: 172.20.0.100

  kafka1:
    image: confluentinc/cp-kafka:7.6.5
    container_name: kafka1
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      tbnet:
        ipv4_address: 172.20.0.110

  # minio:
  #   image: minio/minio:RELEASE.2024-10-29T16-01-48Z-cpuv1
  #   container_name: minio
  #   expose:
  #    - 9000
  #    - 9001
  #   ports:
  #    - "9000:9000"
  #    - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: sderoo
  #     MINIO_ROOT_PASSWORD: sderootpass
  #     MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
  #   volumes:
  #     - ./sde-minio:/data
  #     - ./sde-minio:/root/.minio
  #   command: server /data --console-address ":9001"
  #   networks:
  #     tbnet:
  #       ipv4_address: 172.20.0.249

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: SDE
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
    networks:
      tbnet:
        ipv4_address: 172.20.0.250

networks:
  tbnet:
    ipam:
      config:
        - subnet: 172.20.0.0/16